version: "3.9"

services:
  backend:
    build: ./backend
    container_name: comp3123_backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/comp3123_db
    depends_on:
      - mongo
    command: ["npm", "start"]

  mongo:
    image: mongo
    container_name: comp3123_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: comp3123_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017

volumes:
  mongodb_data:
